name: stacked_localisation_generator
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.google.com

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies: 
  analyzer: '>=2.1.0 <4.0.0'
  build: '>=1.3.0 <3.0.0'
  glob: ^2.0.2
  mustache: ^1.1.1
  path: ^1.8.0
  source_gen: '>=0.9.6 <2.0.0'
  yaml: ^3.1.0


dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  build_test: ^2.1.5
  test: ^1.21.1
